import type { Metadata } from "next";
import "./globals.css";
import Head from "next/head";
import { inter } from "./component/font";
import { ToastContainer } from "react-toastify";
import 'react-toastify/dist/ReactToastify.css';

export const metadata: Metadata = {
  title: "My-Portofolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
      </Head>
      <body
        className={`${inter.className} antialiased`}
      >
        <ToastContainer/>
        {children}
      </body>
    </html>
  );
}
